stages:
    - build
    - test

build-job:
    stage: build
    variables:
        ROOTSYS: /home/alexandregoettel/Software/root/install
    script:
        - echo "Hello, $GITLAB_USER_LOGIN!"
        - export SIM_DIR=$CI_PROJECT_DIR
        - ./RebuildAndInstall_sh.sh

compare-job:
    stage: test
    variables:
        ROOTSYS: /home/alexandregoettel/Software/root/install
    script:
        - echo "Re-building project"
        - export SIM_DIR=$CI_PROJECT_DIR
        - ./RebuildAndInstall_sh.sh
        - echo "Launching fit and comparing..."
        - python test/compareResults.py
